version: '3'

services:

  pgadmin:
    image: dpage/pgadmin4:7.3
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: soporte@test.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    container_name: pgadmin
